### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-wczarnomysy#1]
Buen trabajo @wczarnomysy !

Algunas pistas para acabarlo:

- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] organiza los estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by wczarnomysy** [comment]
Hola Carlos,
Muchas gracias por tu mensaje. He subido la versión mejorada del ejercicio. 
Saludos,
Weronika

**Comment by oneeyedman** [comment]
Bastante bien, @wczarnomysy: Termina esos dos checks que he desmarcado y lo damos por terminado!

**Comment by wczarnomysy** [comment]
Muchas gracias por tu feedback @oneeyedman. Ya he subido las últimas correcciones.

**Comment by oneeyedman** [comment]
Ole, @wczarnomysy! Buen trabajo!
